### ISSUE TITLE
Style issue

### ISSUE THREAD

**Issue by dyckdavid** [dyckdavid/arcoimplements#16]
We got some style issue 
@dtremp007 

![Screenshot 2023-09-07 170815](https://github.com/dyckdavid/arcoimplements/assets/70151610/c80dd85d-c6cf-4ca1-b05f-269d9af67b43)

**Comment by dtremp007** [comment]
I don't have time right now, but I think it has to do with the style on the <main> tag having a max width.

**Comment by dyckdavid** [comment]
No problem if you cant do it now, just wanted to add it as a issue @dtremp007
